Cli
Jonathan-Birkey/CourseProject pull request #10
Opened 2021-11-21 22:04 UTC by Jonathan-Birkey

Converting our scripts into a single CLI application to allow users to generate their own datasets if they wish

2021-11-24 17:13 UTC, dangn2 approved these changes

2021-11-24 17:36 UTC, dangn2 requested changes

2021-11-24 17:36 UTC, dangn2 commented on scrape/scrape.py
> +    time.sleep(2)  # sleep to avoid abusing the API
sleep() in every comments or every symbols, not here, right?

2021-11-25 00:37 UTC, Jonathan-Birkey commented on config.ini
> +[reddit]
they are fake keys, and example config file

2021-11-25 00:39 UTC, Jonathan-Birkey commented on scrape/scrape.py
> +def get_comment_score(comments, score_type='avg'):
that is all @dangn2 !

2021-11-25 01:50 UTC, dangn2 approved these changes

2021-11-25 01:53 UTC, merged